name: test-workspaces
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}